### ISSUE TITLE
关于KeyError: 'GPS GPSLatitude'的问题

### ISSUE THREAD

**Issue by Plutoyer** [xingag/spider_python#2]
自己原图形式测试正常，他人原图形式测试报错
报错代码如下：
Traceback (most recent call last):
  File "C:/Users/Administrator/.PyCharm2017.1/config/皮卡丘/获取女朋友的位置/main.py", line 157, in <module>
    location.run()
  File "C:/Users/Administrator/.PyCharm2017.1/config/皮卡丘/获取女朋友的位置/main.py", line 23, in run
    coordinate = self.__get_image_ability()
  File "C:/Users/Administrator/.PyCharm2017.1/config/皮卡丘/获取女朋友的位置/main.py", line 94, in __get_image_ability
    latitude_gps = img_exif['GPS GPSLatitude']
KeyError: 'GPS GPSLatitude'

**Comment by xingag** [comment]
先判断img_exif是否为空，如果为空，就说明不是原图；如果不为空，可能是相机禁用了地址，没有经度和纬度
